version: '2'
services:
  php:
    build: ./docker/php/
    environment:
      TIMEZONE: Europe/Kiev
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:1.11
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    volumes_from:
      - mysqldata
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=cebep
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpass
      - MYSQL_ROOT_PASSWORD=rootpass

  mysqldata:
    image: debian:jessie
    volumes:
      - /var/lib/mysql

  composer:
    image: composer:1.4
    volumes_from:
      - php
    working_dir: /var/www